### ISSUE TITLE
Error When Opening Empty Files

### ISSUE THREAD

**Issue by iboucher22** [argallmr/pymms#13]
If someone attempts to download data using edi.load_data, and the data contains some empty files and some complete files, one of two errors appears, depending on whether the empty file is the last file opened or it is in the middle of the list of files. 

If it is the last file, 
ValueError: 'Epoch' is not present in all datasets.

If it is in the middle,
ValueError: 'v_labls' not present in all datasets and coords='different'. Either add 'v_labls' to datasets where it is missing or specify coords='minimal'.

Both errors crop up in edi.py on line 111, when the list of files passed in is attempted to be concatenated. It tries to identify 'Epoch' in all the files, and fails to do so since the empty files have no dimensions.

**Comment by argallmr** [comment]
@iboucher22 A date when this happens is Sept 17, 2015 you said?

**Comment by iboucher22** [comment]
Yes, that was the day that was causing errors. There were others but I used that one the most.

On Jun 10, 2021 9:46 AM, Matthew Argall ***@***.***> wrote:
Caution - External Email



@iboucher22<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fiboucher22&data=04%7C01%7Cieb1001%40wildcats.unh.edu%7C18cb99fb52a04304c13108d92c162a8f%7Cd6241893512d46dc8d2bbe47e25f5666%7C0%7C0%7C637589295991642406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4IxRmtN%2FE7aC43kdojmMq6aiGjRpgtofwg4zTH%2FaP58%3D&reserved=0> A date when this happens is Sept 17, 2015 you said?

**Comment by argallmr** [comment]
Empty files are present on Sept. 17, 2017.

An example when the empty file is the first (and only) file in the list:

```
>>> import datetime as dt
>>> from pymms.data import edi
>>> t0 = dt.datetime(2015, 9, 17, 0)
>>> t1 = t0 + dt.timedelta(hours=23, minutes=59, seconds=59)
>>> data = edi.load_data(sc='mms1', mode='srvy', optdesc='efield', start_date=t0, end_date=t1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/argall/Documents/Python/pymms/pymms/data/edi.py", line 98, in load_data
    end_date=end_date, **kwargs)
  File "/Users/argall/Documents/Python/pymms/pymms/data/util.py", line 612, in load_data
    data = data.sel(indexers={rec_vname: slice(start_date, end_date)})
  ...
ValueError: dimensions or multi-index levels ['Epoch'] do not exist
```

An example when it is the middle file:

```
>>> t0 = dt.datetime(2015, 9, 16, 0)
>>> t1 = t0 + dt.timedelta(days=2)
>>> data = edi.load_data(sc='mms1', mode='srvy', optdesc='efield', start_date=t0, end_date=t1)
128kB [00:00, 161MB/s]                                                                                                                           
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/argall/Documents/Python/pymms/pymms/data/edi.py", line 111, in load_data
    data = xr.concat(data, dim='Epoch')
  ...
ValueError: 'v_labls' not present in all datasets and coords='different'. Either add 'v_labls' to datasets where it is missing or specify coords='minimal'.
```

**Comment by argallmr** [comment]
Should be fixed.

If only some of the files are empty, the empty files are silently skipped
```
>>> t0 = dt.datetime(2015, 9, 16, 0)
>>> t1 = t0 + dt.timedelta(days=2)
>>> data = edi.load_data(sc='mms1', mode='srvy', optdesc='efield', start_date=t0, end_date=t1)
```

Note that in the that case all files are empty, an error is still raised.
```
>>> import datetime as dt
>>> from pymms.data import edi
>>> t0 = dt.datetime(2015, 9, 17, 0)
>>> t1 = t0 + dt.timedelta(hours=23, minutes=59, seconds=59)
>>> data = edi.load_data(sc='mms1', mode='srvy', optdesc='efield', start_date=t0, end_date=t1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/argall/Documents/Python/pymms/pymms/data/edi.py", line 98, in load_data
    end_date=end_date, **kwargs)
  File "/Users/argall/Documents/Python/pymms/pymms/data/util.py", line 646, in load_data
    .format(len(files)))
pymms.data.util.NoVariablesInFileError: All 1 files were empty.
```

Also tested for the time interval `t0 = dt.datetime(2017, 7, 11, 0)` to `t1 = t0 + dt.timedelta(days=4)`, which has 2 empty files.
