### ISSUE TITLE
Please assign or clarify code license

### ISSUE THREAD

**Issue by virmitio** [argallmr/pymms#6]
There is currently no license assigned to the repository or any code therein.  This means that all code defaults to "All rights reserved" and does not currently permit anyone to use, modify, expand, etc. any part of this library.

Please consider assigning a license (MIT, BSD, Apache2, etc.) so this code may benefit others.  Otherwise, it seems pointless to leave this as a public repository that nobody has permission to use.

**Comment by argallmr** [comment]
I assigned the MIT license file. Hope this helps.
